SELECT
A.RECID,
A.MODIFIEDDATETIME,
B.REFERENCEID,
CASE WHEN B.REFERENCECATEGORY IN (0,3,13,21,22) THEN D.ENUMLABEL ELSE 'Adjustment' END [CATEGORY],
CASE 
 WHEN A.DATEINVENT != '1900-01-01' 
 THEN A.DATEINVENT
 WHEN A.DATEPHYSICAL != '1900-01-01'
 THEN A.DATEPHYSICAL
 WHEN A.DATEFINANCIAL != '1900-01-01'
 THEN A.DATEFINANCIAL
 ELSE A.DATEEXPECTED
END [DATEID],
C.INVENTLOCATIONID [STOREID],
A.ITEMID,
A.QTY,
CASE WHEN A.COSTAMOUNTPHYSICAL = 0 THEN A.QTY * ISNULL(F.PRICE,0) ELSE A.COSTAMOUNTPHYSICAL END  [COSTAMOUNT],
'UNPOSTED' [INVENTSTATUS]
FROM [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTTRANS AS A
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTTRANSORIGIN AS B ON A.INVENTTRANSORIGIN = B.RECID
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTDIM AS C ON A.INVENTDIMID = C.INVENTDIMID
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.PMCENUMTABLE D ON D.ENUMVALUE = B.REFERENCECATEGORY AND D.ENUMNAME ='InventTransType'
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTLOCATION E ON C.INVENTLOCATIONID = E.INVENTLOCATIONID
LEFT JOIN PHARMACITY_BI_CALCULATE.dbo.VIEW_PRODUCTPURCHASEPRICE F ON A.ITEMID = F.ITEMID
WHERE (((A.STATUSISSUE IN (2,3,4) OR A.STATUSRECEIPT IN (2,3)) AND E.INVENTLOCATIONTYPE NOT IN (1,2)) OR (E.INVENTLOCATIONTYPE = 2 AND A.STATUSISSUE IN (2,3)))
and a.partition =5637144576 and a.DATAAREAID='phct'
and B.partition =5637144576 and B.DATAAREAID='phct'
and C.partition =5637144576 and C.DATAAREAID='phct'
and D.partition =5637144576 and D.DATAAREAID='phct'
and E.partition =5637144576 and D.DATAAREAID='phct'
and a.ITEMID='P16559'
