select X.*,(X.costamount)/(qty) as XX from (SELECT
A.RECID,
A.MODIFIEDDATETIME,
B.REFERENCEID,
a.DATECLOSED,
CASE WHEN B.REFERENCECATEGORY IN (0,3,13,21,22) THEN D.ENUMLABEL ELSE 'Adjustment' END [CATEGORY],
CASE 
 WHEN A.DATEINVENT != '1900-01-01' 
 THEN A.DATEINVENT
 WHEN A.DATEPHYSICAL != '1900-01-01'
 THEN A.DATEPHYSICAL
 WHEN A.DATEFINANCIAL != '1900-01-01'
 THEN A.DATEFINANCIAL
 ELSE A.DATEEXPECTED
END [DATEID],
C.INVENTLOCATIONID [STOREID],
A.ITEMID,
A.QTY,
CASE WHEN A.DATEFINANCIAL != '1900-01-01' THEN A.COSTAMOUNTPOSTED + A.COSTAMOUNTADJUSTMENT ELSE A.COSTAMOUNTPHYSICAL END [COSTAMOUNT],
'POSTED' [INVENTSTATUS]
FROM [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTTRANS AS A
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTTRANSORIGIN AS B ON A.INVENTTRANSORIGIN = B.RECID
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTDIM AS C ON A.INVENTDIMID = C.INVENTDIMID
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.PMCENUMTABLE D ON D.ENUMVALUE = B.REFERENCECATEGORY AND D.ENUMNAME ='InventTransType'
JOIN [SGPMCAXDB10].PHARMACITY_VN_DAX63_LIVE.dbo.INVENTLOCATION E ON C.INVENTLOCATIONID = E.INVENTLOCATIONID
WHERE (A.STATUSISSUE = 1 OR A.STATUSRECEIPT = 1) --AND E.INVENTLOCATIONTYPE NOT IN (1,2)
and a.partition =5637144576 and a.DATAAREAID='phct'
and B.partition =5637144576 and B.DATAAREAID='phct'
and C.partition =5637144576 and C.DATAAREAID='phct'
and D.partition =5637144576 and D.DATAAREAID='phct'
and E.partition =5637144576 and D.DATAAREAID='phct'
and a.ITEMID='P16559'
)X
where X.DATECLOSED between '2022-03-01' and '2022-03-31'
order by x.DATECLOSED desc, x.COSTAMOUNT/x.qty desc

