SELECT B.TRANSACTIONID,
       a.Amount,
       B.RECEIPTID,
       B.CUSTACCOUNT
FROM
  (SELECT A.TRANSACTIONID,
          sum(-A.NETAMOUNTINCLTAX) Amount
   FROM RETAILTRANSACTIONSALESTRANS A
   JOIN RETAILTRANSACTIONTABLE B ON A.TRANSACTIONID = b.TRANSACTIONID
   AND a.TERMINALID = b.TERMINAL
   AND a.STORE = b.STORE
   AND a.partition=5637144576
   AND a.DATAAREAID='phct'
   AND b.partition=5637144576
   AND b.DATAAREAID='phct'
   AND B.ENTRYSTATUS in (0,
                         2)
   AND B.CUSTACCOUNT != 'KH-000001'
   AND B.CUSTACCOUNT != ''
   WHERE A.STORE in
       (SELECT RTC.STORENUMBER
        FROM PMCGiftCardProgramPriceGroup GCPG
        JOIN PriceDiscGroup PG-- RETAILCHANNELPRICEGROUP PG
 ON GCPG.PRICEGROUP = PG.recid
        JOIN RETAILCHANNELPRICEGROUP RTPG ON RTPG.PRICEGROUP = PG.RECID
        JOIN RETAILCHANNELTABLE RTC ON RTC.recid = RTPG.RETAILCHANNEL
        WHERE GCPG.PMCGIFTCARDPROGRAMID='GC-001327'
          AND GCPG.partition=5637144576
          AND GCPG.DATAAREAID='phct'
          AND PG.partition=5637144576
          AND PG.DATAAREAID='phct'
          AND RTPG.partition=5637144576
          AND RTPG.partition=5637144576 )
     AND A.TRANSDATE >='2022-08-22'
     AND a.TRANSACTIONSTATUS in (0,
                                 2)
     AND NOT EXISTS
       (SELECT 1
        FROM PMCGiftCardProgramItem
        WHERE PMCGiftCardProgramItem.ITEMID = A.ITEMID
          AND PMCGIFTCARDPROGRAMID='GC-001327'
          AND PARTITION=5637144576
          AND DATAAREAID='phct')
     AND NOT EXISTS
       (SELECT 1
        FROM RETAILGIFTCARDTRANSACTIONS T1
        JOIN RETAILGIFTCARDTABLE T2 ON T2.ENTRYID = T1.CARDNUMBER
        AND T2.PMCGIFTCARDPROGRAMID='GC-001327'
        AND T1.partition=5637144576
        AND T1.DATAAREAID='phct'
        AND T2.partition=5637144576
        AND T2.DATAAREAID='phct'
        WHERE a.TRANSACTIONID = T1.TRANSACTIONID)
   GROUP BY a.TRANSACTIONID
   HAVING sum(-A.NETAMOUNTINCLTAX)>=500) A
JOIN RETAILTRANSACTIONTABLE B ON A.TRANSACTIONID =b.TRANSACTIONID
AND b.partition=5637144576
AND b.DATAAREAID='phct'
